name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: [2.4.x, 2.5.x, 2.6.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Ruby ${{ matrix.ruby-version }}
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
    - name: Rubocop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v1.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
